
baseurl: "ngx-dynamic-forms" # the subpath of your site, e.g. /blog
url: "https://guilherme-fafic.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

